language: python
os: linux
dist: xenial
git:
    submodules: true
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"
install:
    - sudo curl -sSL https://get.haskellstack.org/ | sh
    - stack --version
    - pip install -r requirements.txt
    - python -m pip install --ignore-installed -r requirements-dev.txt
script:
    pytest

