language: python
os: linux
dist: xenial
git:
    submodules: true
cache:
    directories:
        - $HOME/.local/bin
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"
install:
    - if [ ! -f .local/bin/stack ]; then sudo curl -sSL https://get.haskellstack.org/ | sh; fi
    - stack --version
    - pip install -r requirements.txt
    - python -m pip install --ignore-installed -r requirements-dev.txt
script:
    - python test/test_cases.py
    - pytest

